name: CI

on:
  push:
    branches: ["main", "master"]
  pull_request:
    branches: ["main", "master"]

jobs:
  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install pnpm
        run: npm i -g pnpm@8
      - name: Install frontend deps
        run: pnpm install --frozen-lockfile
        working-directory: FrontEnd
      - name: Typecheck
        run: pnpm run typecheck
        working-directory: FrontEnd
      - name: Build client
        run: pnpm run build:client
        working-directory: FrontEnd

  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'
      - name: Build solution
        run: |
          dotnet restore SaMapViewer/SaMapViewer.csproj
          dotnet build SaMapViewer/SaMapViewer.sln --configuration Release --no-restore
